// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alcnyantkqllpwyylsxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsY255YW50a3FsbHB3eXlsc3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Njk2MjQsImV4cCI6MjA2NDI0NTYyNH0.p_pOvTuA_LGFqU-LoWFB00dgib9nRmnSfOK453nCv_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);